version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: echo "Hello, CircleCI!"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
